# RUN initial CODE

In [1]:
import numpy as np
import pandas as pd
from IPython.display import display, Math

def general_primal_to_dual(objective, c, A, b, constraints):
    """
    Converts a general primal LP problem into its dual.

    Primal Problem:
    - Objective: 'maximize' or 'minimize'
    - c: array of objective function coefficients
    - A: 2D array of constraint coefficients
    - b: array of right-hand side values
    - constraints: array of constraint types ('<=', '>=', '=')

    The function handles the duality rules for different constraint and
    variable types.
    """
    c = np.array(c, dtype=float)
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    
    m, n = A.shape  # m = number of constraints, n = number of variables

    # Dual problem components will be built based on the primal's structure
    dual_objective = ""
    dual_c = np.array([])
    dual_A = np.array([])
    dual_b = np.array([])
    dual_vars = []

    # --- Step 1: Formulate the Dual Objective ---
    if objective == 'maximize':
        dual_objective = 'Minimize'
        dual_c = b
    elif objective == 'minimize':
        dual_objective = 'Maximize'
        dual_c = c

    # --- Step 2: Formulate the Dual Constraints (A^T y) and RHS (c) ---
    # The dual coefficient matrix is the transpose of the primal's
    dual_A = A.T
    dual_b = c

    # --- Step 3: Determine Dual Variable Types based on Primal Constraints ---
    for i, constr_type in enumerate(constraints):
        if objective == 'maximize':
            if constr_type == '<=':
                dual_vars.append('>= 0')
            elif constr_type == '>=':
                dual_vars.append('<= 0')
            elif constr_type == '=':
                dual_vars.append('unrestricted')
        elif objective == 'minimize':
            if constr_type == '>=':
                dual_vars.append('>= 0')
            elif constr_type == '<=':
                dual_vars.append('<= 0')
            elif constr_type == '=':
                dual_vars.append('unrestricted')

    # --- Step 4: Determine Dual Constraint Types based on Primal Variables ---
    dual_constr_types = []
    # Assuming primal variables are >= 0. If they were different, this would change.
    # For a general primal problem with all variables >= 0, the dual constraints will be based on the objective type.
    for _ in range(n):
        if objective == 'maximize':
            dual_constr_types.append('>=')
        elif objective == 'minimize':
            dual_constr_types.append('<=')
    
    # --- Start of LaTeX Formatting ---
    
    # Primal
    latex_primal = f"$$\\text{{Primal Problem (P):}}\n\\text{{{objective.capitalize()} }} Z = "
    for i, coeff in enumerate(c):
        latex_primal += f"{coeff}x_{{{i+1}}}" + (" + " if i < len(c) - 1 else "")
    latex_primal += " \\\\\n\\text{Subject to:}\n"
    for i in range(m):
        latex_primal += " \\\\\n"
        for j, coeff in enumerate(A[i]):
            latex_primal += f"{coeff}x_{{{j+1}}}" + (" + " if j < n - 1 else "")
        latex_primal += f" {constraints[i]} {b[i]}"
    latex_primal += "\\\\\n"
    latex_primal += "x_1, \\dots, x_n \\geq 0\n$$"

    # Dual
    latex_dual = f"$$\\text{{Dual Problem (D):}}\n\\text{{{dual_objective} }} W = "
    for i, coeff in enumerate(dual_c):
        latex_dual += f"{coeff}y_{{{i+1}}}" + (" + " if i < len(dual_c) - 1 else "")
    latex_dual += " \\\\\n\\text{Subject to:}\n"
    for i in range(len(dual_constr_types)):
        latex_dual += " \\\\\n"
        for j, coeff in enumerate(dual_A[i]):
            latex_dual += f"{coeff}y_{{{j+1}}}" + (" + " if j < dual_A.shape[1] - 1 else "")
        latex_dual += f" {dual_constr_types[i]} {dual_b[i]}"
    latex_dual += "\\\\\n"
    
    # Dual variable types
    for i, var_type in enumerate(dual_vars):
        latex_dual += f"y_{{{i+1}}} {var_type}" + (", " if i < len(dual_vars) - 1 else "")
    latex_dual += "\n$$"

    display(Math(latex_primal))
    display(Math(latex_dual))

    return dual_objective, dual_c, dual_A, dual_b, dual_vars, dual_constr_types


# 5

In [2]:

c1 = [5, 4, -1, 3]
A1 = [[3, 2,-3, 1], 
      [3, 3, 1, 3]]
b1 = [24, 36]
constraints1 = ['<=', '<=']
general_primal_to_dual('maximize', c1, A1, b1, constraints1)

<IPython.core.display.Math object>

<IPython.core.display.Math object>

('Minimize',
 array([24., 36.]),
 array([[ 3.,  3.],
        [ 2.,  3.],
        [-3.,  1.],
        [ 1.,  3.]]),
 array([ 5.,  4., -1.,  3.]),
 ['>= 0', '>= 0'],
 ['>=', '>=', '>=', '>='])

# 6

In [4]:

c1 = [2, -1, 1]
A1 = [[3, 1, 1], 
      [1, -1, 2],
      [1, 1, -1]
      ]
b1 = [60, 10, 20]
constraints1 = ['<=', '<=', '<=']
general_primal_to_dual('maximize', c1, A1, b1, constraints1)

<IPython.core.display.Math object>

<IPython.core.display.Math object>

('Minimize',
 array([60., 10., 20.]),
 array([[ 3.,  1.,  1.],
        [ 1., -1.,  1.],
        [ 1.,  2., -1.]]),
 array([ 2., -1.,  1.]),
 ['>= 0', '>= 0', '>= 0'],
 ['>=', '>=', '>='])